In [140]:
from collections import defaultdict
from typing import Iterable
from itertools import chain

import numpy as np


def parser(file = 'input.txt'):
    with open(file, 'r') as file:
        for line in file:
            yield line.strip('\n')

def solver(lines: Iterable[str]):
    lines = [*lines]
    grid = [(y, x) for y, row in enumerate(lines) for x, char in enumerate(row) if char == '#']
    rocks = []
    for x in range(len(lines[0])):
        grid.append((-1, x))
    for y, row in enumerate(lines):
        for x, char in enumerate(row):
            if char != 'O':
                continue
            m = max(filter(lambda y_x: y_x[0] <= y and y_x[1] == x, chain(grid, rocks)), key=lambda y_x: y_x[0])
            rocks.append((m[0]+1, x))
    # print('\n'.join(
    #     ''.join(
    #         '#' if (y, x) in grid else ('O' if (y,x) in rocks else '.')
    #         for x, char in enumerate(row)
    #     ) + f" {len(lines) - y:02}"
    #     for y, row in enumerate(lines)
    # ))
    return sum(len(lines) - y for (y, _x) in rocks)



def transform(matrix):
    for y, row in enumerate(matrix):
        for x, cell in enumerate(row):
            if cell != 'O':
                continue
            ty = y
            # print("O", y, x)
            while True:
                ty =ty-1 
                # if (y,x) == (1,2): print(ty < 0, matrix[ty][x] in 'O#')
                if ty < 0 or matrix[ty][x] in 'O#':
                    # print('M', ty, x)
                    matrix[y][x] = '.'
                    matrix[ty+1][x] = 'O'
                    break
            # print('\n'.join(''.join(row) for row in matrix), '\n')


def p(matrix):
    print('\n'.join(''.join(row) for row in matrix), '\n')

def solver2(lines: Iterable[str]):
    matrix = np.array([[*r] for r in lines])
    
    cycle = 0
    N = 1_000_000_000
    cache = {}
    while (cycle:=cycle+1) <= N:
        # print("NORTH")
        # p(matrix)
        transform(matrix)
        # p(matrix)
        
        # print("WEST")
        matrix = matrix.transpose()
        # print(matrix)
        transform(matrix)
        

        # print("SOUTH")
        matrix = np.flip(matrix.transpose())
        # print(matrix)
        transform(matrix)

        # print("EAST")
        matrix = matrix.transpose()
        # print(matrix)
        transform(matrix)

        # print("NORTH")
        matrix = np.flip(matrix).transpose()
        # print(matrix)

        h = tuple(tuple(row) for row in matrix)
        if h in cache:
            cycles_between_repeat = cycle - cache[h]
            distance_to_end = N - cycle
            cycle += distance_to_end - distance_to_end%cycles_between_repeat
        cache[h] = cycle

    # print(matrix)

    # print('\n'.join(
    #     ''.join(
    #         '#' if (y, x) in grid else ('O' if (y,x) in rocks else '.')
    #         for x, char in enumerate(row)
    #     ) + f" {len(lines) - y:02}"
    #     for y, row in enumerate(lines)
    # ))
    return sum(len(matrix) - y for y, row in enumerate(matrix) for _x, cell in enumerate(row) if cell == 'O')


if __name__ == '__main__':
    test = solver(parser('test_input.txt'))
    print(test)
    assert test == 136
    print(solver(parser()))

    test = solver2(parser('test_input.txt'))
    print(test)
    assert test == 64, test
    print(solver2(parser()))

136
108813
64
104533


In [141]:
import numpy as np

def transpose(matrix):
    return [[matrix[y][x] for y in range(len(matrix))] for x in range(len(matrix[0]))]

print("NORTH")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


print("WEST")
matrix = matrix.transpose()
print(matrix)

print("SOUTH")
matrix = np.flip(matrix.transpose())
print(matrix)

print("EAST")
matrix = matrix.transpose()
print(matrix)

print("NORTH")
matrix = np.flip(matrix).transpose()
print(matrix)



NORTH
[[1 2 3]
 [4 5 6]
 [7 8 9]]
WEST
[[1 4 7]
 [2 5 8]
 [3 6 9]]
SOUTH
[[9 8 7]
 [6 5 4]
 [3 2 1]]
EAST
[[9 6 3]
 [8 5 2]
 [7 4 1]]
NORTH
[[1 2 3]
 [4 5 6]
 [7 8 9]]
