In [1]:
from pprint import pprint
from typing import Iterable
import numpy as np


def parser(file = 'input.txt'):
    with open(file, 'r') as file:
        for pattern in file.read().split("\n\n"):
            yield pattern


def solver(inp: Iterable[str], part = 1):
    part  -= 1
    patterns = [[line for line in lines.split('\n')] for lines in inp]
    total = 0
    for rows in patterns:
        # print(rows)
        width = len(rows[0])
        columns = [''.join(row[col_idx] for row in rows) for col_idx in range(width)]
        # r, c = f(rows), f(columns)
        # print(r, c)
        for y, line in enumerate(rows[1:], start=1):
            a, b = rows[y:], rows[:y][::-1]
            if sum(b != o for boven, onder in zip(a, b) for b, o in zip(boven, onder)) == part:
                # print(y)
                total += y*100
        for x, line in enumerate(columns[1:], start=1):
            a, b = columns[x:], columns[:x][::-1]
            if sum(l != r for links, rechts in zip(a, b) for l, r in zip(links, rechts)) == part:
                # print(y)
                total += x
    print(total)
    return total


if __name__ == '__main__':
    test = solver(parser('test_input.txt'))
    print(test)
    assert test == 405, test
    print(solver(parser()))
    assert solver(parser()) == 29213

    test = solver(parser('test_input.txt'), 2)
    print(test)
    assert test == 400, test
    print(solver(parser(), 2))

405
405
29213
29213
29213
400
400
37453
37453


In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.transpose(arr))
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
