In [110]:
from typing import Iterable
import numpy as np


def parser(file = 'input.txt'):
    with open(file, 'r') as file:
        for pattern in file.read().split("\n\n"):
            yield pattern

pairs = lambda iterable: (a:=iter(iterable), b:=iter(iterable), next(b), zip(a,b))[-1]


def solver(inp: Iterable[str]):
    patterns = [[line for line in lines.split('\n')] for lines in inp]
    total = 0
    for rows in patterns[:1]:
        print(rows)
        width = len(rows[0])
        height = len(rows)
        columns = [''.join(row[col_idx] for row in rows) for col_idx in range(width)]
        possible_col, possible_row = 0, 0
        print("columns")
        for idx in range(1, width//2+1):          
            print(idx, idx+1)
            l,r = columns[:idx], columns[idx:idx*2][::-1]
            print(l, r)
            if (l==r):
                print("match", l, r, idx)
            l,r = columns[-idx:], columns[-idx*2:-idx][::-1]
            print("invert", l, r)
            if (l==r):
                print("match", l, r, idx)
        print("rows")
        for idx in range(1, height//2+1):
            print(idx, idx+1)
            l,r = rows[:idx], rows[idx:idx*2][::-1]
            print(l, r)
            if (l==r):
                print("match", l, r, idx)
            l,r = rows[-idx:], rows[-idx*2:-idx][::-1]
            print("invert", l, r)
            if (l==r):
                print("match", l, r, idx)
            
        print(possible_col, possible_row)


    print(total)
    return total



if __name__ == '__main__':
    test = solver(parser('test_input.txt'))
    print(test)
    assert test == 405, test
    # print(solver(parser()))

['#.##..##.', '..#.##.#.', '##......#', '##......#', '..#.##.#.', '..##..##.', '#.#.##.#.']
columns
1 2
['#.##..#'] ['..##...']
invert ['..##...'] ['##..###']
2 3
['#.##..#', '..##...'] ['#....#.', '##..###']
invert ['##..###', '..##...'] ['#....#.', '.#..#.#']
3 4
['#.##..#', '..##...', '##..###'] ['.#..#.#', '.#..#.#', '#....#.']
invert ['#....#.', '##..###', '..##...'] ['.#..#.#', '.#..#.#', '#....#.']
4 5
['#.##..#', '..##...', '##..###', '#....#.'] ['##..###', '#....#.', '.#..#.#', '.#..#.#']
invert ['.#..#.#', '#....#.', '##..###', '..##...'] ['.#..#.#', '#....#.', '##..###', '..##...']
match ['.#..#.#', '#....#.', '##..###', '..##...'] ['.#..#.#', '#....#.', '##..###', '..##...'] 4
height
1 2
['#.##..##.'] ['..#.##.#.']
invert ['#.#.##.#.'] ['..##..##.']
2 3
['#.##..##.', '..#.##.#.'] ['##......#', '##......#']
invert ['..##..##.', '#.#.##.#.'] ['..#.##.#.', '##......#']
3 4
['#.##..##.', '..#.##.#.', '##......#'] ['..##..##.', '..#.##.#.', '##......#']
invert ['..#.##.#.', '..#

AssertionError: 0

In [88]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.transpose(arr))
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
