In [46]:
from skimage.morphology import flood_fill
RED = '\033[91m'
BLUE = '\033[94m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
SQUARE = '■'
BLOCK = '\u2588'
RESET = '\033[0m'
RED_BLOCK = RED + BLOCK + RESET
BLUE_BLOCK = BLUE + BLOCK + RESET
GREEN_BLOCK = GREEN + BLOCK + RESET
YELLOW_BLOCK = YELLOW + BLOCK + RESET

In [7]:
import numpy as np

from enum import Enum
from typing import Iterable

import numpy as np


def parser(file = 'input.txt'):
    with open(file, 'r') as file:
        for line in file:
            yield line.strip('\n')


LEFT = (0, -1)
RIGHT = (0, 1)
UP = (-1, 0)
DOWN = (1, 0)

def f(queue, dist, matrix, counter, curr, source):
    y, x = curr
    valid = {
        DOWN: '|JL',
        UP: '|F7',
        RIGHT: '-J7',
        LEFT: '-LF',
    }
    translate = {
        '|': {UP:UP, DOWN:DOWN},
        '-': {LEFT:LEFT, RIGHT:RIGHT},
        'J': {DOWN:LEFT, RIGHT:UP},
        'L': {DOWN:RIGHT, LEFT:UP},
        '7': {RIGHT:DOWN, UP:LEFT},
        'F': {LEFT:DOWN, UP:RIGHT}
    }
    char = matrix[y][x]
    # print(char)
    if char == 'S':
        for new in (LEFT, RIGHT, UP, DOWN):
            dy, dx = new
            ny, nx = y+dy, x+dx
            if not (0 <= ny < len(matrix) and 0 <= nx < len(matrix[0])):
                continue
            if matrix[ny][nx] not in valid[new]:
                continue
            if (ny, nx) not in dist:
                dist[(ny, nx)] = counter + 1
                queue.append((counter+1, (ny, nx), new))
            elif dist[(ny, nx)] > counter:
                dist[(ny, nx)] = counter + 1
                queue.append((counter+1, (ny, nx), new))
    else:
        # print("else")
        dy, dx = new = translate[char][source]
        ny, nx = y+dy, x+dx
        if not (0 <= ny < len(matrix) and 0 <= nx < len(matrix[0])):
            # print("not inside")
            return
        if matrix[ny][nx] not in valid[new]:
            # print("not valid", curr, (ny,nx),matrix[ny][nx], valid[new], char, translate[char][source])
            return
        if (ny, nx) not in dist:
            # print("Not in")
            dist[(ny, nx)] = counter + 1
            queue.append((counter+1, (ny, nx), new))
        elif dist[(ny, nx)] > counter:
            # print("In but count")
            dist[(ny, nx)] = counter + 1
            queue.append((counter+1, (ny, nx), new))
        else:
            print("Huh")
        # print(f"{source=}, {translate[char][source]=}")
    


def solver(matrix: Iterable[str]):
    matrix = [*matrix]
    starts = [(y, x) for y, _ in enumerate(matrix) for x, _ in enumerate(matrix[y]) if matrix[y][x] == 'S']
    print(starts)
    assert len(starts) == 1
    y, x = start = starts[0] # type: ignore
    dist = {start:0}
    queue= [(0, start, None)]
    print(dist, queue)
    for task in queue:
        _counter, (y, x), _source = task
        f(queue, dist, matrix, *task)
        # print(dist, queue, task)
        # break
    m  = max(dist.values())
    if m<= 9:
        print('\n'.join(''.join(str(dist.get((y, x), '.')) for x,_ in enumerate(matrix[y])) for y, _ in enumerate(matrix)))
    return m, dist


In [48]:
from pprint import pprint


def parser(file = 'input.txt'):
    with open(file, 'r') as file:
        for line in file:
            yield line.strip('\n')

matrix = [*parser('test_input_p2_3.txt')] # 1e S
matrix = [*parser('input.txt')] # 2e S
_, dist = solver(matrix)
orig_matrix = matrix

S = [
    [0, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
]
S = [
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
]

upsize = {
        '|' : [
            [0, 1, 0],
            [0, 1, 0],
            [0, 1, 0],
        ],
        '-' : [
            [0, 0, 0],
            [1, 1, 1],
            [0, 0, 0],
        ],
        'L' : [
            [0, 1, 0],
            [0, 1, 1],
            [0, 0, 0],
        ],
        'J' : [
            [0, 1, 0],
            [1, 1, 0],
            [0, 0, 0],
        ],
        '7' : [
            [0, 0, 0],
            [1, 1, 0],
            [0, 1, 0],
        ],
        'F' : [
            [0, 0, 0],
            [0, 1, 1],
            [0, 1, 0],
        ],
        'S' : S
    }
empty = [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ]
matrix = [[cell if (y,x) in dist else '.' for x,cell in enumerate(row)] for y,row in enumerate(matrix)]
a2d = np.array([[upsize[matrix[y][x]] if (y,x) in dist else empty  for x,_ in enumerate(matrix[y])] for y, _ in enumerate(matrix)])
# flood_fill(a, (1,1), 9)
# pprint(matrix)
# pprint(a2d)
a2d = np.array([[upsize[matrix[y][x]] if matrix[y][x] in upsize else empty  for x,_ in enumerate(matrix[y])] for y, _ in enumerate(matrix)])
print(a2d.shape)
# print(a2d.reshape((2, 6, 3)))
new = np.concatenate(a2d[0, :])
print(np.array([[np.concatenate(a2d[m, :])[:, i] for i in range(3)] for m in range(len(matrix))]))

[(26, 31)]
{(26, 31): 0} [(0, (26, 31), None)]
Huh
Huh
(140, 140, 3, 3)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [49]:
raise Exception("niet deze cell perongelijk runnen dombo")
matrix = [
    ".F-L-.",
    ".|...J"
]
matrix = [
    "........",
    ".S----7.",
    ".|F--7|.",
    ".||..||.",
    ".|L7FJ|.",
    ".|.||.|.",
    ".L-JL-J.",
    "........",
]
a2d = np.array([[upsize[matrix[y][x]] if matrix[y][x] in upsize else empty  for x,_ in enumerate(matrix[y])] for y, _ in enumerate(matrix)])
print(a2d.shape)
# print(a2d.reshape((2, 6, 3)))
# new = np.concatenate(a2d[0, :])
# print(np.array([[np.concatenate(a2d[m, :])[:, i] for i in range(3)] for m in range(len(matrix))]))

Exception: niet deze cell perongelijk runnen dombo

In [50]:
y, x = 2, 6  # Example dimensions, replace these with your actual dimensions
arr = np.random.randint(1, 10, size=(y, x, 3, 3))
arr = a2d
y, x, *_ = a2d.shape

# Reshape and concatenate the array
result = arr.swapaxes(1, 2).reshape(y * 3, x * 3)

# print("Original array:")
# print(arr)
# print("\nTransformed array:")
# print(result)
flooded = flood_fill(result, (0,0), 8)
print(flooded)

[[8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 ...
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]]


In [51]:
# Revert the transformation
reverted = flooded.reshape(y, 3, x, 3).swapaxes(1, 2)

height = y
width  = x
print("Transformed array:")
# print(transformed_arr)
print("\nReverted array:")
# print(reverted)
rev ='\n'.join(''.join(str(int((cell == 8).all())) for cell in row  )for row in reverted)
revls = rev.split('\n')
print(rev)
flooded_list = [(y, x) for y, row in enumerate(rev.split('\n'))  for x, cell in enumerate(row) if cell=='1']

Transformed array:

Reverted array:
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111100011100111001111111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111100011100111000011111111111111111111111111111111
11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110010000100000011111111111111111111111111111111
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110000000000000000001111111111

In [52]:
t = reverted[1][2]
print((t == 8))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [53]:
print(
'\n'.join([
    ''.join([
        matrix[y][x] if (y, x) in dist else ('O' if revls[y][x] == '1' else ('#' if matrix[y][x] != '.' else 'I'))
        for x in range(len(matrix[0]))
    ])
    for y in range(len(matrix))
])
)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOF-7OOOF7OOOF7OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL7|OOO||OOO||F7OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO||OF-J|OF7|LJ|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOF7F7|L7L-7L7||L7FJOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOO

In [54]:
fin = '\n'.join([
    ''.join([
        '.' if (y, x) in dist else ('O' if revls[y][x] == '1' else ('#' if matrix[y][x] != '.' else 'I'))
        for x in range(len(matrix[0]))
    ])
    for y in range(len(matrix))
])
print(
    fin
)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...OOO..OOO..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...OOO..OOO....OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..O....O......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOO

In [55]:
print(fin.count('I'))

477


In [56]:
print(
'\n'.join([
    ''.join([
        matrix[y][x] if (y, x) in dist else ((GREEN_BLOCK if revls[y][x] == '1' else YELLOW_BLOCK) if orig_matrix[y][x] != '.' else (BLUE_BLOCK if revls[y][x] == '1' else RED_BLOCK))
        for x in range(len(matrix[0]))
    ])
    for y in range(len(matrix))
])
)

████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████████████████████████████████F-7███F7███F7██████████████████████████████████
█████████████████████████████████████████████████████████████████████████████████████████████L7|███||███||F7████████████████████████████████
██████████████████████████████████████████████████████████████████████████████████████████████||█F-J|█F7|LJ|████████████████████████████████
██████████████████████████████████████████████████████████████████████████████████████████F7F7|L7L-7L7||L7FJ████████████████████████████████
█████████████